version: '3'

# deployed locally at ~/assetServer

services:
  assets:
    image: python:alpine
    container_name: sftaAssets
    ports:
      - '8083:8083'
    volumes:
      - ./:/home/
    command: [sh, -c, 'cd /home && python -m http.server 8083']