# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://vagrantcloud.com/search.
  
  # Ubuntu Server
  #config.vm.box = "bento/ubuntu-18.04"
  # config.vm.box = "boxcycler/linuxmint-19-cinnamon-64bit-v2-release"
  # config.vm.box_version = "19.0.0"
  
  #config.vm.box = "npalm/mint17-amd64-cinnamon"
  #config.vm.box_version = "2016.01.19"

	config.vm.box = "peru/ubuntu-18.04-desktop-amd64"
  	#config.vm.box_version = "20181210.01"
  	

  # set name of new vm
  config.vm.provider "virtualbox" do |v|
    v.name = "Ubuntu Manual Testserver Pipeline"
    v.memory = 3000
  	v.cpus = 2
  end


  # add a public network and add a static IP
  config.vm.network "public_network", ip: "192.168.50.3", bridge: "wlp3s0"


  config.vm.provider "virtualbox" do |vb|
    config.vm.network "private_network", ip: "192.168.50.3"
  end

  # set ports which should be forwarded
  #config.vm.network 'forwarded_port', guest: 8080, host: 8080, id: 'aaa'
  config.vm.network 'forwarded_port', guest: 8081, host: 8081, id: 'bbb'
  #config.vm.network 'forwarded_port', guest: 8085, host: 8082, id: 'bbb'


  # install docker
  config.vm.provision "docker"
 


end
